FROM python:3.11-slim

WORKDIR /app

COPY src/python_run /app

# Install dependencies
RUN pip3 install -e .
RUN pip3 install -r requirements.txt
RUN pip3 install -r requirements_http.txt

COPY models /app/models

EXPOSE 5000

CMD python3 -m piper.http_server -m /app/models/en_GB-alan-medium.onnx